version: "3"
services:
  cosmos:
    image: buildkite/puppeteer:8.0.0
    user: root
    working_dir: /app
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
    volumes:
      - .:/app
      - node_modules:/app/node_modules/
    entrypoint: /bin/sh -c
    command:
      - yarn --frozen-lockfile && yarn cosmos
  regression:
    image: buildkite/puppeteer:8.0.0
    user: root
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - USER=root
      - CIRCLE_NODE_TOTAL
      - CIRCLE_NODE_INDEX
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
    entrypoint: ["/bin/bash", "-c"]
    command:
      - npx wait-on http://cosmos:5001 && yarn jest --clearCache && yarn run visual-regression:exec
    depends_on:
      - cosmos

volumes:
  node_modules:
